### ISSUE TITLE
Error: Overriding declaration requires an 'override' keyword

### ISSUE THREAD

**Issue by zummenix** [krzyzanowskim/Natalie#10]
![untitled](https://cloud.githubusercontent.com/assets/3009258/7226883/f5c2d6ce-e765-11e4-8785-61709c8a7a4c.png)
In our project `SettingsMessageViewController` is subclass of other controller.

**Comment by krzyzanowskim** [comment]
hum... is this a setup where SettingsMesasgeViewController inherit from another class where storyboardIdentifier is defined as well ?

**Comment by zummenix** [comment]
@krzyzanowskim Yes it is

**Comment by krzyzanowskim** [comment]
sorry silly, question, I see you wrote it is. Though I have to think how to deal with this.

**Comment by zummenix** [comment]
@krzyzanowskim You can add `storyboardIdentifier` property to the UIViewController and override it later:

``` swift
extension UIViewController {
    class var storyboardIdentifier:String { return "" }
}

class SomeViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        NSLog(SomeViewController.storyboardIdentifier)
    }
}

class OtherViewController: SomeViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        NSLog(OtherViewController.storyboardIdentifier)
    }
}

extension SomeViewController {
    override class var storyboardIdentifier:String { return "SomeViewController" }
}

extension OtherViewController {
    override class var storyboardIdentifier:String { return "OtherViewController" }
}
```

It solves problem only with `storyboardIdentifier` property. I'm not sure how `enum Segue` will work in the case of subclassing.

**Comment by krzyzanowskim** [comment]
Very good solution! I'll go with this for the fix.
Yes segues are next.

**Comment by krzyzanowskim** [comment]
Segue enum is fine because nested enum type is bound to the type and is not inherited
