### ISSUE TITLE
Always up to date

### ISSUE THREAD

**Issue by Henawey** [krzyzanowskim/Natalie#101]
the script always says I'm up to date even if there are a changes

**Comment by phimage** [comment]
Talking about script into build phase which contains test code ?
```
if [ ! -e "$OUTPUT_PATH" ] || [ -n "$(find "$BASE_PATH" -type f -name "*.storyboard" -newer "$OUTPUT_PATH" -print -quit)" ]; then
```

Tested just now, and each time I modify, the Storyboards.swift is regenerated
Check your Storyboards.swift last modification date. Maybe some weird date has been set.

**Comment by phimage** [comment]
This issue has been closed because there hasn't been any activity.
