### ISSUE TITLE
Inheritance errors

### ISSUE THREAD

**Issue by hefgi** [krzyzanowskim/Natalie#103]
If I have a class who inherit from an other one, here's what I get :

<img width="844" alt="screen shot 2017-08-03 at 14 58 35" src="https://user-images.githubusercontent.com/216584/28938591-8465baf2-785c-11e7-937f-a0b68945cba7.png">

**Comment by phimage** [comment]
I think there is no information in storyboard XML to know if a controller has inheritance.
But I have a solution that can be implemented.
In interface builder, natalie user must click on its controller (here QRReaderViewController), then "Identity Inspector", and add a "User Definied Runtimes Attributes" like "natalie.inherit" of type boolean to true

In natalie code we can read the userDefinedRuntimeAttributes of controller to add override or not
I can do it after swift 4

**Comment by phimage** [comment]
duplicate #78 #10 and fixed
