### ISSUE TITLE
Custom UINavigationController class in multiple storyboards causes build errors

### ISSUE THREAD

**Issue by aspyre** [krzyzanowskim/Natalie#104]
If I have two storyboards, both containing a UINavigationController which inherits from a custom class (eg. CustomNavigationController), the resulting Storyboards.swift file does not compile. It fails with "'CustomNavigationController IdentifiableProtocol' is ambiguous for type lookup in this context" errors.

See attached sample project.

Is there a possible fix or workaround?

[NatalieBug.zip](https://github.com/krzyzanowskim/Natalie/files/1260777/NatalieBug.zip)

**Comment by phimage** [comment]
You must create two more navigation controller which inherit from `CustomNavigationController`
FirstNavigationController and SecondNavigationController for instance

So each will be extended with a `storyboardIdentifier`, a different one for each
