### ISSUE TITLE
Swift 4 issue in console 

### ISSUE THREAD

**Issue by den-ree** [krzyzanowskim/Natalie#105]
Hi, @krzyzanowskim) thanks for the lib, after migrating on Swift 4, I have this issue:

*** ......../Storyboards/Storyboards.swift:535:5: implicit Objective-C entrypoint -[_VIEW CONTROLLER CLASS NAME_ storyboardIdentifier] is deprecated and will be removed in Swift 4; add explicit '@objc' to the declaration to emit the Objective-C entrypoint in Swift 4 and suppress this message

Do you know how to fix it?

**Comment by krzyzanowskim** [comment]
Closing as duplicate https://github.com/krzyzanowskim/Natalie/issues/106

**Comment by phimage** [comment]
I think it's not the same issue

Here the code generated by Natalie is not fully compatible with swift 4

TODO
- [x] Before that, a tag (0.5.1) or/and a branch for last version compatible with swift3.2
- [x] Update  SWXMLHash to 4.2.3 (swift 4)
- [x] Set project to swift 4 (Natalie and demo)
- [x] Fix Natalie compil issues
- [x] Generate Storyboards.swift on iOS, macOS to see errors
- [x] Update Natalie to output compatible code without errors
- [ ] Check deprecation of static storyboardIdentifier (this bug issue), check some compile flags

**Comment by phimage** [comment]
https://github.com/phimage/Natalie/commit/1c746ddaf05952092cbe9c073563bb11c4879be0 ( https://github.com/phimage/Natalie/tree/feature/swift4  )
I have some test to do before PR

**Comment by phimage** [comment]
@Den-Ree in build settings your Swift 3 @objc Inference is set to Defaults, On or Off?
And If you change, something change on warning?

**Comment by krzyzanowskim** [comment]
I just released [0.6.0](https://github.com/krzyzanowskim/Natalie/releases/tag/0.6.0)

**Comment by den-ree** [comment]
@krzyzanowskim thanks.
