### ISSUE TITLE
./scripts/build.sh - doesn't seem to work

### ISSUE THREAD

**Issue by alkalim** [krzyzanowskim/Natalie#111]
Hello,

The build.sh script doesn't seem to build anything.

```
BUILD_PATH=`xcrun swift build -c release --static-swift-stdlib --show-bin-path`
cp "$BUILD_PATH/natalie" .
echo "Binary at path $PWD/natalie"
```
It looks like SPM doesn't build anything and just prints bin build path if --show-bin-path option is given

It builds fine if you just run `swift build -c release --static-swift-stdlib`

Can I submit PR for this?

**Comment by krzyzanowskim** [comment]
oh my. Sure, please submit PR
