### ISSUE TITLE
natalie binary of 0.6.5 does not work after updating to Xcode 9.3

### ISSUE THREAD

**Issue by Fab1n** [krzyzanowskim/Natalie#119]
Executing `natalie`, even with no arguments, in commandline throws an error like this:
`dyld: Symbol not found: __T0s11CommandLineO9argumentsSaySSGvZ`.

`swift --version` outputs the following after switching command-line-tools back to 9.2 (9C40b):
_Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)_
_Target: x86_64-apple-macosx10.9_

If I build the natalie project in Xcode 9.2 or 9.3 and execute the generated executable it just works fine. 

Maybe the natalie executable is not compatible with the updated swift version in the system?

**Comment by krzyzanowskim** [comment]
the Swift ABI beauty. Need to rebuild with new Swift compiler version (then won't be compatible with the previous Swift version of course)

**Comment by Fab1n** [comment]
The fun part is, I switched command line tools back to 9.2 after installing 9.2 again in parallel. Then still does not work :/

**Comment by krzyzanowskim** [comment]
yeap. needs to rebuild and push. I'm guessing you installed via homebrew?

**Comment by Fab1n** [comment]
nope, we include it as submodule in our project

**Comment by broadwaylamb** [comment]
There is a `-static-stdlib` compiler flag that maybe can help this until ABI stability comes.

**Comment by krzyzanowskim** [comment]
(I forgot I added the binary to the repo)

The script to update the binary:
```shell
./scripts/build.sh
```

I'm pushing the updated binary now

**Comment by Fab1n** [comment]
Ah cool, ok. I built the binary with Xcode, didn't know of the script. Building it with Xcode somehow makes it work in both cases (systems with Xcode 9.3 and systems with 9.2).

Thanks for your work.

**Comment by Fab1n** [comment]
Verified, your newly pushed executable is compatible with 9.3 and 9.2 environments.

**Comment by alkalim** [comment]
The file size grew 20x times compared to the previous version :(
![screen shot 2018-04-11 at 15 03 28](https://user-images.githubusercontent.com/33055344/38616233-ead7befc-3d9b-11e8-9f98-33d5754730a5.png)

**Comment by Fab1n** [comment]
Yes that’s true, I noticed this yesterday...

**Comment by krzyzanowskim** [comment]
static linking comes with the price.
