### ISSUE TITLE
Swiftlint issues

### ISSUE THREAD

**Issue by aabanaag** [krzyzanowskim/Natalie#120]
Tried implementing Natalie to my project added xcode integration but storyboards.swift has swiftlint issues. Also I created Storyboards.swift on ProjectName/Common folder but can't seem to find the generated one. Any ideas? 

![image](https://user-images.githubusercontent.com/2245822/40771399-d3b7d7ae-64ef-11e8-81b7-daf8ec3e7e64.png)

**Comment by krzyzanowskim** [comment]
You may want skip the generated file from the SwiftLint rules.

**Comment by phimage** [comment]
I create a PR #121

**Comment by aabanaag** [comment]
thanks! but is there a possibility to specify the path where Storyboards.swift should be created?

**Comment by phimage** [comment]
@aabanaag that another question!
Generate it, do a `cp`
