### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by aabanaag** [krzyzanowskim/Natalie#123]
I always get this error whenever I try to checkout other branch in Xcode.
```
could not remove '/Users/account/Documents/Code/App/Company/project-app/PROJ/Storyboards.swift': Operation not permitted (-1)
```

Any ideas?

**Comment by phimage** [comment]
do in terminal an ls -s '/Users/account/Documents/Code/App/Company/project-app/PROJ/Storyboards.swift'

and check the file right

do a chmod if necessary

--

or maybe the file do no exist

**Comment by aabanaag** [comment]
I did a chmod onto the Storyboards.swift file but with no luck still has operation not permitted whenever I switch onto another branch. I have to delete the file first before I can switch the generate it again. Also I'm seeing a lock icon lower left of the file icon.

**Comment by krzyzanowskim** [comment]
The file is locked by the Xcode script

**Comment by aabanaag** [comment]
I have to delete the Storyboards.swift (locked) file then do a revert in xcode after that I can switch branch.

**Comment by krzyzanowskim** [comment]
Modify the script to not lock the file

**Comment by aabanaag** [comment]
![image](https://user-images.githubusercontent.com/2245822/41041024-9374f88a-69d0-11e8-90ca-9f3d134a0943.png)

Sorry, but I just copied the script from the readme. how would I modify the script to not lock the file?

**Comment by krzyzanowskim** [comment]
Comment out lines with "chflags"

**Comment by aabanaag** [comment]
Thanks.
