### ISSUE TITLE
Special processing for customModuleProvider="target" for view controllers?

### ISSUE THREAD

**Issue by alkalim** [krzyzanowskim/Natalie#125]
When you start fresh storyboard with one target the view controller definition in the storyboard looks like this:

```xml
<viewController id="BYZ-38-t0r" customClass="ViewController" customModuleProvider="target" sceneMemberID="viewController">
```
Given that Inherit module from target option is on and you don't assign module explicitly.
However when you define more targets and assign this storyboard to them at some point Xcode adds customModule attribute but leaves customModuleProvider="target" as is:
```xml
<viewController id="BYZ-38-t0r" customClass="ViewController" customModule="mytarget1" customModuleProvider="target" sceneMemberID="viewController">
```
Apparently it goes unnoticed because customModuleProvider has a higher precedence over customModule and is just not used during class load if customModuleProvider="target" is specified.

However Natalie processes customModule attribute regardless of customModuleProvider which results in fully qualified class names. For example, if I have targets mytarget1 and mytarget2 and the storyboard "remembers" customModule="mytarget1" Natalie will generate the following code:
```swift
static func instantiateInitialViewController() -> mytarget1.ViewController {
        return self.storyboard.instantiateInitialViewController() as! mytarget1.ViewController
}
```
Which will not build for mytarget2.

I would propose to add a special case in ViewController.swift, property customClassWithModule :
Change:
`            if let moduleName = self.customModule {`
To:
`            if let moduleName = self.customModule, customModuleProvider != "target" {`

**Comment by phimage** [comment]
Hi, 
could you PR?
Maybe edit one of the example to be able to test it

**Comment by alkalim** [comment]
> could you PR?

Done!

> Maybe edit one of the example to be able to test it

I have tested it with the following steps:

- Compiled and run the original NatalieExample successfully

- Duplicated target NatalieExample which failed to compile:

<img width="1316" alt="screen shot 2018-06-20 at 01 13 14" src="https://user-images.githubusercontent.com/33055344/41627970-1d430d22-742b-11e8-882d-830d2ca7b91d.png">

- Applied the patch, compiled and run NatalieExampleCopy successfully.

- The result Storyboards.swift changes look allright as well:

<img width="931" alt="screen shot 2018-06-20 at 01 25 21" src="https://user-images.githubusercontent.com/33055344/41628103-b57c0e2c-742b-11e8-84d9-e061c62e68ca.png">
