### ISSUE TITLE
How do you handle when you delete storyboards?

### ISSUE THREAD

**Issue by aabanaag** [krzyzanowskim/Natalie#127]
I deleted storyboard(s) from my project and Storyboards.swift is causing the build to fail. How do you fix the issue where you don't go manually and comment-out Storyboards.Board from all of the code?

**Comment by phimage** [comment]
Build failed? Why do not provide the errors, this could help

Then did you regenerate the file using natalie after deleting your storyboard?

**Comment by aabanaag** [comment]
![image](https://user-images.githubusercontent.com/2245822/44326924-cfe57480-a48f-11e8-90e9-b9718259ce9c.png)

sorry for the late response, got side tracked doing something else. anyways, here is the sample error. I'm using the build script to generate the storyboards.swift but since I deleted a storyboard it is throwing an error above. If I delete the storyboards.swift I would end-up commenting all of the references in my project for Storyboards.xxxx which is kinda cumbersome.

**Comment by phimage** [comment]
If you regenerate the Storyboards.swift file, you have BadgeViewController not in the same compilation target or not in your project but in your file system

You can specify the folder to look for storyboards files

**Comment by aabanaag** [comment]
Got it by manually regenerating the file from the terminal. I initially thought the build script can handle such task. Thanks by the way!
