### ISSUE TITLE
File generation refactor

### ISSUE THREAD

**Issue by chrisfsampaio** [krzyzanowskim/Natalie#16]
We need to be able to analyse the generated file before printing it (see #15). Say if we need to remove duplicated imports, or move all the imports to the file head, that cannot be done with the current setup.
My suggestion is to hold the generated file on a string and do the post analysis before _outputing_ it.

Does that make sense? Any thoughts?

**Comment by phimage** [comment]
Other way to do it, its to make a function or computed var in StoryboardFile
func customImports() -> [String] inspired from processStoryboard() to loop on viewControllers, and with your code to extract custommodule

Then in processStoryboards() after the first import, loop on storyboardFiles, create a set of all imports and print it

**Comment by krzyzanowskim** [comment]
#18 is somehow related.
