### ISSUE TITLE
UIViewController subclasses from separate modules/frameworks breaks generated file

### ISSUE THREAD

**Issue by yoiang** [krzyzanowskim/Natalie#18]
If one's `.storyboard` includes a View Controller subclass defined in a module/framework that must normally be imported the generated file will have to import it as well.

**Comment by krzyzanowskim** [comment]
This was somehow addressed here: https://github.com/krzyzanowskim/Natalie/commit/27d58abee2fddf8786b6392836892b7c463a5e16

**Comment by krzyzanowskim** [comment]
@yoiang can you please attach sample Storyboard with this issue?

**Comment by krzyzanowskim** [comment]
@yoiang I think it's about how you call natalie.swift script. If you add path to frameworks where .storyboard filse is available it will be used by Natalie

**Comment by yoiang** [comment]
@krzyzanowskim Sorry, I don't think I fully understand what you mean by adding the path to the frameworks where the storyboard files are available. Can you provide an example? 

Sorry, I haven't been able to take time to make a sample Storyboard myself but I can say that on this project we're using Cocoapods and a VC from a Library in a Cocoapod.

**Comment by krzyzanowskim** [comment]
`natalie.swift /path1 /path2 /path3`

**Comment by yoiang** [comment]
Gotcha, so this would only work for a precompiled framework?

**Comment by yoiang** [comment]
It appears my issue is a [problem with Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/3620), thanks @krzyzanowskim for the assistance!
