### ISSUE TITLE
There is no possibility to instantiate view controller

### ISSUE THREAD

**Issue by jestspoko** [krzyzanowskim/Natalie#2]
probably two problems:
1. variable "storyboardIdentifier" in viewcontroller's extension should be a class var
2. variable "storyboardIdentifier" gets viewcontroller's "id" not "storyboardIdentifier"

**Comment by krzyzanowskim** [comment]
agree, would you PR for that ?

**Comment by krzyzanowskim** [comment]
thanks, Pull request merged
https://github.com/krzyzanowskim/Natalie/pull/3
