### ISSUE TITLE
Segues tied to gesture recognizers (non-manual segues) aren't processed

### ISSUE THREAD

**Issue by jai** [krzyzanowskim/Natalie#20]
So if a segue appears outside the `viewController` element in the `objects` element, then it doesn't get indexed/processed, as in here - the `ShopImageSegue` won't appear in the generated swift file. I don't have a solution yet but wanted to post it here.

```
    <scene sceneID="04j-HW-gGp">
        <objects>
            <tableViewController storyboardIdentifier="RBShopDetailViewController" id="NHg-Ry-QDF" customClass="RBShopDetailViewController" customModule="Ramen_Beast" customModuleProvider="target" sceneMemberID="viewController">
                <connections>
                //
                    //MANUAL SEGUES APPEAR HERE
                    //

                </connections>
            </tableViewController>
            <placeholder placeholderIdentifier="IBFirstResponder" id="Hjv-Px-2Va" userLabel="First Responder" sceneMemberID="firstResponder"/>
            <tapGestureRecognizer id="OXk-v3-cJn" userLabel="Left Image Tap Recognizer">
                <connections>
                    <outlet property="delegate" destination="NHg-Ry-QDF" id="Kbi-ot-jDB"/>
                    <segue destination="Yqq-hT-2nd" kind="show" identifier="ShopImageSegue" id="kFM-z9-bmD"/>
                </connections>
            </tapGestureRecognizer>
            <tapGestureRecognizer id="fHf-lD-POd" userLabel="Right Image Tap Recognizer"/>
        </objects>
        <point key="canvasLocation" x="2288" y="-349"/>
    </scene>
```

**Comment by krzyzanowskim** [comment]
This issue was addressed here #11. I assume it's not enough ?

**Comment by jai** [comment]
Nope and I'm guessing it's because while buttons, etc are subviews and so live inside the `viewController` element, gesture recognizers are seen at the 'same' level and are outside the `viewController` element while being inside the same `scene` element...so we need to enumerate all of these potential items while making sure they relate back to the view controller. Will spend a bit of time on it.

**Comment by jai** [comment]
See if this makes sense: https://github.com/jai/Natalie/commit/0c339284db040ac75535c8a7e4cce20de434768f

The only part I don't like is:

```
let viewController = searchAll(scene, "sceneMemberID", "viewController")![0]
```

I don't know enough about storyboard file structures to know if scenes and view controllers are tied to a 1-1 relationship and if not then this would break

I haven't updated the example project yet but testing it in my own project, seems to work. Need to do that before I submit a PR.

**Comment by jai** [comment]
PR: https://github.com/krzyzanowskim/Natalie/pull/21

**Comment by krzyzanowskim** [comment]
ok, please update PR according to the last cosmetic comment and I'm willing to merge changes. Thanks!

**Comment by jai** [comment]
Updated PR
