### ISSUE TITLE
When using a view class from a framework, you get an undeclared type error

### ISSUE THREAD

**Issue by ldiqual** [krzyzanowskim/Natalie#37]
Since natalie doesn't know what frameworks to import, the generated `Storyboards.swift` file triggers undeclared type errors for all external classes.

![](https://www.dropbox.com/s/d20dwgui4c8g1cw/Screenshot%202015-06-13%2022.12.06.png?raw=1)

**Comment by phimage** [comment]
there is already some code to add import for external module 

``` swift
if viewController.showCustomImport() {
    println("import \(viewController.customModule)")
```

for this purpose, when you choose your view controller, you must have specified the module under the class choice

maybe due to code change, the import are now not at the good place (since 2bf28a0b1977248a0239776044accb3d7679fd6e )
I can share on monday a code that move the import at the begining of the generated file

**Comment by ldiqual** [comment]
@phimage I looked into my `Main.storyboard` and found out that there was no `customModule` associated with the `ECSlidingViewController` instance:

```
<viewController id="HFB-xO-gCW" customClass="ECSlidingViewController" sceneMemberID="viewController">
```

![](https://www.dropbox.com/s/lsm7huve1b5zulx/Screenshot%202015-06-15%2023.20.39.png?raw=1)

so there is no way for natalie to know which framework to import.

Do you have any idea why Xcode would not import from the ECSlidingViewController framework (added via Cocoapods), or how to fix the issue?

**Comment by phimage** [comment]
Yes, there is no module for objective-c framework, I don't know how to fix that without custom config files for natalie or command line parameter
Or explain in the doc that import must be added manually for objective-c framework after each generations...

I have tested with `ECSlidingViewController`
Trying to force module to ECSlidingViewController, I have a funny `import Optional("ECSlidingViewController")`
The place of `import` in swift have no incidence so PR #41 its just to have a more clean code

**Comment by krzyzanowskim** [comment]
yeap. it must be defined by the user in the Interface Builder. Can't be handled in runtime. Too complicated to scan whole project/workspace looking for modules and match classess.

**Comment by phimage** [comment]
I think it's a real bug or a limitation to document somewhere (no objective c controller allowed or add import manually)

Maybe a MyStoryBoardName.natalie near the storyboardfile could define some code to inject or properties like "imports" to add in generated files

**Comment by ldiqual** [comment]
@krzyzanowskim I second @phimage 's comment. Having external framework references in a storyboard is a pretty common thing, now that many projects use cocoapods. I would suggest to at least leave the issue open so someone could look into it.

**Comment by krzyzanowskim** [comment]
should be mentioned somewhere in the docs.
