### ISSUE TITLE
Sample project 

### ISSUE THREAD

**Issue by masters3d** [krzyzanowskim/Natalie#4]
Am I missing something?

![image](https://cloud.githubusercontent.com/assets/6539412/7203350/d6040cca-e4ce-11e4-9369-f2ff22eb2a27.png)

**Comment by krzyzanowskim** [comment]
is generated file available to the project ? (is it generated and added to the project?). Bear in mind that  (in case of integration with Xcode) it have to be prior to compilation phase.

**Comment by krzyzanowskim** [comment]
ah, Now I see it's sample project.

sample project assume that you have installed natalie.swift in /usr/local/bin directory

**Comment by masters3d** [comment]
Does the generated code need to have natalie.swift installed?

**Comment by krzyzanowskim** [comment]
no, it's just not generated by default, Storyboards.swift file is empty. You can generate it manually.
Now I see maybe it is better to add pregenerated file to sample project to avoid such confusion.

**Comment by krzyzanowskim** [comment]
Overall "installation process" have to be improved over the time.

**Comment by masters3d** [comment]
I think this code this missing from the sample project. 
![image](https://cloud.githubusercontent.com/assets/6539412/7203750/c9fd63ce-e4d1-11e4-8c09-7ddab53f5870.png)
![image](https://cloud.githubusercontent.com/assets/6539412/7203815/50928432-e4d2-11e4-86d5-53ce7c7c1035.png)

**Comment by krzyzanowskim** [comment]
I can't confirm here lack of these parts. Do you have file generated after all ?

if you have /usr/local/bin/natalie.swift then it should build and compile without issues. Just remember to use Xcode 6.3 for command line tools.

**Comment by masters3d** [comment]
Ahh. I was assuming this sample project to be a sample of the output of the script.

**Comment by krzyzanowskim** [comment]
and thanks to you it will be. There is no reason not to be actually. Thank you.

**Comment by masters3d** [comment]
cool. It would be cool to see the before script is applied. After script
"Sample Result" . I really like the Idea behind the script. Thank you
