### ISSUE TITLE
Some code is generated even when it's not used

### ISSUE THREAD

**Issue by kostiakoval** [krzyzanowskim/Natalie#42]
UICollectionViewController and UITableViewController extension is generated even when they are not used in the application. 
The code should be generated only when they are used. It would make code cleaner.

Steps : 
- Remove all from the storyboard 
- Save and build, generate it.

The files contains 145 lines of code.

I see 2 improvements: 
- Don't generated code that not used
- Move some base functionality to separate file, if it's possible.

**Comment by kostiakoval** [comment]
One of the solution to merge natalie.swift would be run script before building it. 
Would be very useful for development. 

`cat a.swift b.swift > natalie.swift`

**Comment by phimage** [comment]
Two way for Reusable
1 - print all stuff about `UICollectionViewController` and `UITableViewController` after calling `processViewControllers` (which know if reuseIdentifier has been detected)
2 - detect if there is a not empty "reuseIdentifier" attribute with something like that

``` swift
let noReusable = [Reusable]()
let reusables = storyboards.flatMap{
  $0.storyboard?.scenes.flatMap{
    $0.viewController?.reusables?.filter{
        return $0.reuseIdentifier != nil
    } ?? noReusable
  } ?? noReusable
}
let hasReusable = !reusables.isEmpty
```

yes If we want to develop in separate files and want to concatenate all files in natalies.swift we can use a script like this
https://github.com/evgenyneu/moa/blob/master/scripts/concatenate_swift_files.sh

**Comment by phimage** [comment]
In PR #47
- I print only code about Reusable/reuseidentifier  (UICollectionViewController and UITableViewController ) only if needed
- remove comment "MARK : controller name" is no segue or reuse identifier
  For the generated example : https://github.com/krzyzanowskim/Natalie/pull/47/files

@kostiakoval have you seen other codes to not print ? If none, this issue could be closed after PR #47 merge? (maybe we can discuss about split files elsewhere like in #43)

**Comment by krzyzanowskim** [comment]
Why the whole "ReusableProtocol" is out in this PR ?

**Comment by krzyzanowskim** [comment]
ReusableProtocol describe what is already in UIKit. It's good to have it around with extensions, no matter if Natalie generated something reusable or not.

I think this change is unnecessary.
