### ISSUE TITLE
XNatalie for Xcode7

### ISSUE THREAD

**Issue by krzyzanowskim** [krzyzanowskim/Natalie#51]
XNatalie plugin need update to Xcode 7 on branch Swift20 cc @phimage

**Comment by phimage** [comment]
I can't install for the moment Xcode7 on my computer
I test on Xcode 7 beta 1 on friend computed, I don't see any issues except adding the UUID of current XCode
But new beta could have break the plugin

**Comment by krzyzanowskim** [comment]
I tested it on some later beta and it crashed.

**Comment by phimage** [comment]
I see you have updated code and add UUID for beta 3 763b97aae5e9aa4fd6c293fc329bd03f6513c895
So I tested with beta 3

I have no problem (on OSX 10.10.3)
But I do some project configuration change to test it :  
- Edit Scheme > Run > Info (tab)
- Change Executable to Xcode-beta.app

But when Xcode7 will be the main Xcode, this change will be no more necessary
So I don't know If it is necessary to commit this change (to remove it later)
