### ISSUE TITLE
I like your name. 

### ISSUE THREAD

**Issue by robertzk** [krzyzanowskim/Natalie#6]
That is all.

**Comment by krzyzanowskim** [comment]
Hi Robert, he have so much letters in common :-)

**Comment by bronikowski** [comment]
WONTFIX… uh, sorry, wrong thread. ;-)

**Comment by kostiakoval** [comment]
How about closing this one? :)

**Comment by yzhong52** [comment]
wait, why leaving an issue open if it is not a real issue...
