### ISSUE TITLE
objc-codegenutils

### ISSUE THREAD

**Issue by fabb** [krzyzanowskim/Natalie#7]
How does this compare to `objc-codegenutils`? Would be nice to see some synergy between the two projects.

https://github.com/square/objc-codegenutils
This is a very good fork that also generates Swift code: https://github.com/rocket0423/objc-codegenutils

**Comment by krzyzanowskim** [comment]
thank you for this question. I hope you find my answer complete in that regard.

I have checked linked project now. Both are somehow similar when it comes to the fact that you can get identifiers for strings, and basically this is what is in common. 

Both are different concepts when it comes to implementation. I think that **Natalie** approach is more complementary. 

**objc-identifierconstants** generates list of identifiers for string, for example:

``` swift
let MainStoryboardName = "Main"
let MainStoryboardDuplicatePushIdentifier = "DuplicatePush"
```

**Natalie** on the other hand generate series of extensions to the objects found in Storyboard, thanks to what developer have organized structure that clearly relate to identifiers in storyboard hierarchy, like this in this examples:

``` swift
MainViewController.Segue.ScreenOneSegue
MainViewController.Segue.ScreenOneSegue.kind
MainViewController.Segue.ScreenOneSegue.destination
MainViewController.storyboardIdentifier

Storyboards.Main.instantiateInitialViewController()
```

Segues are nested inside the proper view controller class as enums... I believe this is the more complementary approach than simple listing of strings as variables.

What I would like to archive is access to objects defined by Storyboard with code and to receive properties defined in storyboard file, transparently, without strings and in convenient yet readable form.

**Comment by fabb** [comment]
Thank you for your thorough answer! I guess as long as I'm using a mixed Objective-C/Swift project, I will not be able to use Natalie from the Objective-C parts?

**Comment by krzyzanowskim** [comment]
I'm not sure. It would require some @objc here and there. You can play with it and prepare PullRequest if it is feasible.
