### ISSUE TITLE
Error: Value of optional type 'UIViewController?' not unwrapped; did you mean to use '!' or '?'?

### ISSUE THREAD

**Issue by LukasGram** [krzyzanowskim/Natalie#70]
One of my Storyboards uses an UIViewController without any custom class. After the Storyboard.swift is generated I get the error in the following function:

```
static func instantiateInitialViewController() -> UIViewController {
   return self.storyboard.instantiateInitialViewController()
}
```

I'm using the Swift 2.0 version of Natalie.

**Comment by krzyzanowskim** [comment]
ah, it changes between SDK versions, and differ in iOS and Mac. Need to double check this one.

**Comment by krzyzanowskim** [comment]
how come hm.... it should be something like this, with `as!`

```
        static func instantiateInitialViewController() -> UINavigationController {
            return self.storyboard.instantiateInitialViewController() as! UINavigationController
        }
```

**Comment by LukasGram** [comment]
In one of my Storyboards the initial view controller is an `UIViewController`.
But `self.storyboard.instantiateInitialViewController() as! UIViewController` would not make sense since `instantiateInitialViewController()` returns `UIViewController?`
So it needs to look like this: `self.storyboard.instantiateInitialViewController()!`

Already created a pull request (#71) which should fix this.
