### ISSUE TITLE
New issue after XCode 7 installarion

### ISSUE THREAD

**Issue by TheTonon** [krzyzanowskim/Natalie#72]
I'm having a new issue after xcode 7 kicked in. I have 2 xcode installations now, one with 6.4 and one with 7. The only thing that doesn't pass during the build phase is Natalie. It throws me "Command /bin/sh failed with exit code 133" 

and "Natalie generator
dyld: Library not loaded: @rpath/libswiftSecurity.dylib
  Referenced from: /usr/local/bin/natalie.swift
  Reason: image not found"

and "/usr/local/bin/natalie.swift "$PROJECT_DIR/$PROJECT_NAME" > "$PROJECT_DIR/$PROJECT_NAME/Layout/Storyboards.swift""

Anyone has the same issue? Did I mess up when doubling the installation?

**Comment by krzyzanowskim** [comment]
did you update /usr/local/bin/natalie.swift with the one from repository ?

**Comment by krzyzanowskim** [comment]
Either update `/usr/local/bin/natalie.swift` with the current one, or change path to version appropriate to your project
Natalie v 0.2 is for Xcode 6.0
Natalie v 0.3 is for Xcode 7.0

**Comment by TheTonon** [comment]
Solved it. Since I didn't told Homebrew to update, I thought it would not do it. 

Many thanks.

**Comment by dalu93** [comment]
@krzyzanowskim I have the same problem on Xcode 7.3 with natalie 0.4 installed with Homebrew

**Comment by krzyzanowskim** [comment]
I will take a look for Xcode 7.3 compatibiluy later today

**Comment by dalu93** [comment]
@krzyzanowskim Any news? May should I open a new issue since this one is closed?

**Comment by krzyzanowskim** [comment]
may need rebuild binary with homebrew. Meantime please use script version downloaded from the repo.

**Comment by dalu93** [comment]
Ok, downloading the **.swift** file and replacing the existing one in my machine solved the problem
