### ISSUE TITLE
"Unknown controller element: viewControllerPlaceholder:"

### ISSUE THREAD

**Issue by tomhut** [krzyzanowskim/Natalie#74]
Hi, when trying to run Natalie I am getting the following error.

"fatal error: Unknown controller element: viewControllerPlaceholder: file /usr/local/bin/natalie.swift, line 733"

It this because I am using multiple storyboards and Natalie does not yet support the storyboard segues?

Any help greatly appreciated.

Build phase log:
https://gist.github.com/tomhut/ff952ac4a7d7e09856e9

**Comment by krzyzanowskim** [comment]
uh, yes. It should be ignored in this case I think, not fatal error.

**Comment by tomhut** [comment]
@krzyzanowskim Thanks, problem is, after being run the Storyboards.swift file is generated but empty. (Sorry, should have stated this in the original issue)

**Comment by krzyzanowskim** [comment]
@tomhut  would you mind attach sample `Storyboard.storyboard` file here?

**Comment by krzyzanowskim** [comment]
it should skip the "viewControllerPlaceholder" without error (assert)
