### ISSUE TITLE
Xcode Integration problem

### ISSUE THREAD

**Issue by CallumOz** [krzyzanowskim/Natalie#8]
First of all.
Thank you, this tool is a great idea.

Unfortunately, I am having issues with the Xcode Integration, I am using Xcode 6.3.

Everything goes well when running natalie.swift from the command line.
I have copied natalie.swift to /usr/local/bin.

I have added the script to the build phases like so:
![Build phases screen capture](https://infinit.io/link/Callum_Henshall/u2NMyZF.png)

When Xcode does it's automatic building it seems to work, the Storyboards.swift file is updated.
However, when I build or run the app, I get many errors:
![Errors](https://infinit.io/link/Callum_Henshall/N6naRpm.png)

I hope I am just missing something.

Callum

**Comment by krzyzanowskim** [comment]
I assume the errors are related to natalie.swift execution, so when you remove natalie execution, you don 't have these errors.

Please verify your command line setup, this setting determine swift binary used by shell.
![asf](http://f.cl.ly/items/142l0J0h3l3D202z1A3s/Screen%20Shot%202015-04-19%20at%2018.39.53.png)

**Comment by krzyzanowskim** [comment]
btw. you can verify project setup with NatalieExample project from the repository

**Comment by CallumOz** [comment]
I just opened the NatalieExample project and I get the same problem.

Command line setup:
![Xcode Settings](https://infinit.io/link/Callum_Henshall/fBMUHuT.png)

I don't see any differences.

**Comment by krzyzanowskim** [comment]
Strange, it should behave is the very same as launched from command line. You can try replace first line of `natalie.swift` to:

```
#!/usr/bin/swift
```

maybe this is somehow related in your setup.

**Comment by krzyzanowskim** [comment]
and please, try this one as it may be the actual solution

```
#!/usr/bin/env xcrun -sdk macosx swift
```

ale let me know if that helps.

**Comment by CallumOz** [comment]
![Bingo!](http://i.giphy.com/W5dBnWmcGDABi.gif)
The last one seems to fix the problem.

**Comment by krzyzanowskim** [comment]
✌️thanks, fixed.
