### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by aromal-sasidharan** [krzyzanowskim/Natalie#88]
Whenever I tried to generate storyboard code that has storyboardID for a storyboard reference, the Natalie execution stops and raises an error  **_"unexpectedly found nil while unwrapping an Optional value
Illegal instruction: 4" _** - See image attached for more understanding

![sample](https://cloud.githubusercontent.com/assets/5155674/14582699/1ea9a70c-042a-11e6-90d2-09fa97d64501.gif)

**Comment by aromal-sasidharan** [comment]
Please solve this issue ASAP. It will be helpful. Thanks. Have a Great Day!

**Comment by krzyzanowskim** [comment]
Can you attach sample storyboard file that cause the problem ?

**Comment by aromal-sasidharan** [comment]
You can find the whole sample project here. https://github.com/CodebaseiPHONE/NatalieError

**Comment by bartleby** [comment]
+1 when will update ?

**Comment by bartleby** [comment]
i go to R.Swift =)

**Comment by krzyzanowskim** [comment]
Fixed. finally.
